let users = [
  {
    info: {
      username: "Domak",
      email: "domak@audrey.tulip",
      password: "password",
      profile: "./assets/images/domak.jpg",
      agreeNoti: "on",
    },
    progress_course: [],
    finished_lessons: [],
    my_schedules: [],
    finished_quiz: [],
  },
  {
    info: {
      username: "Kyaw Thura",
      email: "kyawthura@audrey.tulip",
      password: "password",
      profile: "./assets/images/kyawthura.jpg",
      agreeNoti: "on",
    },
    progress_course: [],
    finished_lessons: [],
    my_schedules: [],
    finished_quiz: [],
  },
  {
    info: {
      username: "Thiha Naing",
      email: "thihanaing@audrey.tulip",
      password: "password",
      profile: "./assets/images/thiha.jpg",
      agreeNoti: "on",
    },
    progress_course: [],
    finished_lessons: [],
    my_schedules: [],
    finished_quiz: [],
  },
  {
    info: {
      username: "Hla Moe Oo",
      email: "hlamoeoo@audrey.tulip",
      password: "password",
      profile: "./assets/images/hlahla.jpg",
      agreeNoti: "on",
    },
    progress_course: [],
    finished_lessons: [],
    my_schedules: [],
    finished_quiz: [],
  },
  {
    info: {
      username: "Zaw Zay Shine",
      email: "zawzayshine@audrey.tulip",
      password: "password",
      profile: "./assets/images/zzs.jpg",
      agreeNoti: "on",
    },
    progress_course: [],
    finished_lessons: [],
    my_schedules: [],
    finished_quiz: [],
  },
  {
    info: {
      username: "Zaw Lin Naing",
      email: "zawlinnaing@audrey.tulip",
      password: "password",
      profile: "./assets/images/zawlinnaing.jpg",
      agreeNoti: "on",
    },
    progress_course: [],
    finished_lessons: [],
    my_schedules: [],
    finished_quiz: [],
  },
  {
    info: {
      username: "Phyoe Pyae Maung",
      email: "phyoepyaemaung@audrey.tulip",
      password: "password",
      profile: "./assets/images/phyoepyaemg.jpg",
      agreeNoti: "on",
    },
    progress_course: [],
    finished_lessons: [],
    my_schedules: [],
    finished_quiz: [],
  },
  {
    info: {
      username: "Nyan Lin Soe",
      email: "nyanlinsoe@audrey.tulip",
      password: "password",
      profile: "./assets/images/nyanlinsoe.jpg",
      agreeNoti: "on",
    },
    progress_course: [],
    finished_lessons: [],
    my_schedules: [],
    finished_quiz: [],
  },
];

export default users;
